(function(d,c){"function"===typeof define&&define.amd?define("background/store/fileDetails",[],c):d.FileDetails=c()})("undefined"!==typeof self?self:this,function(){var d=function(a){this.mimeType=a.mimeType||a.mimeType_;this.streamURL=a.streamURL||a.streamURL_;this.originalURL=a.originalURL||a.originalURL_;this.preferredFilename=a.preferredFilename||a.preferredFilename_;this.driveDocId=a.driveDocId||a.driveDocId_;this.driveDocResourceKey=a.driveDocResourceKey||a.driveDocResourceKey_;this.embedded=
a.embedded||a.embedded_;this.userFile=a.userFile||a.userFile_;this.newDocument=a.newDocument;this.tabId=a.tabId||a.tabId_;this.privateFilePath=a.privateFilePath||a.privateFilePath_;this.downloadFilePath=a.downloadFilePath||a.downloadFilePath_;this.timestamp=a.timestamp||a.timestamp_;this.observerFunc_=void 0;Object.seal(this)};d.prototype=Object.create(Object.prototype,{tabId:{set:function(a){this.tabId_=a;this.invokeObserver_()},get:function(){return this.tabId_}},privateFilePath:{set:function(a){this.privateFilePath_=
a;this.invokeObserver_()},get:function(){return this.privateFilePath_}},downloadFilePath:{set:function(a){this.downloadFilePath_=a;this.invokeObserver_()},get:function(){return this.downloadFilePath_}},timestamp:{set:function(a){this.timestamp_=a;this.invokeObserver_()},get:function(){return this.timestamp_}},mimeType:{set:function(a){this.mimeType_=a;this.invokeObserver_()},get:function(){return this.mimeType_}},streamURL:{set:function(a){this.streamURL_=a;this.invokeObserver_()},get:function(){return this.streamURL_}},
originalURL:{set:function(a){this.originalURL_=a;this.invokeObserver_()},get:function(){return this.originalURL_}},preferredFilename:{set:function(a){this.preferredFilename_=a;this.invokeObserver_()},get:function(){return this.preferredFilename_}},userFile:{set:function(a){this.userFile_=a;this.invokeObserver_()},get:function(){return this.userFile_}},driveDocId:{set:function(a){this.driveDocId_=a;this.invokeObserver_()},get:function(){return this.driveDocId_}}});d.prototype.constructor=d;d.prototype.addObserver=
function(a){"function"===typeof a&&(this.observerFunc_=a)};d.prototype.hasExpired=function(){return!this.tabId&&(new Date).getTime()-this.timestamp>c};d.prototype.toJSON=function(){var a=Object.assign({},this);a.userFile_=void 0;return a};var c=7776E6;d.prototype.invokeObserver_=function(){this.observerFunc_&&this.observerFunc_()};return d});
(function(d,c){"function"===typeof define&&define.amd?define("background/store/fileStore",["background/store/fileDetails"],c):d.FileStore=c(d.FileDetails)})("undefined"!==typeof self?self:this,function(d){var c,a=function(){return new Promise(function(a){chrome.storage.local.get(["qo_file_store"],function(b){b=b.qo_file_store;c=!b||0===Object.keys(b).length&&b.constructor===Object?{}:JSON.parse(b);for(var e in c)b=new d(c[e]),b.addObserver(k),c[e]=b;a()})})},k=function(){var a;a=JSON.stringify(c);
chrome.storage.local.set({qo_file_store:a},function(){})},m=function(){var a=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var c=(a+16*Math.random())%16|0;a=Math.floor(a/16);return("x"===b?c:c&7|8).toString(16)})};return{init:function(){return a()},addEntry:function(a){var b;a instanceof d&&(a.addObserver(k),b=m(),c[b]=a,k());return b},addMissingEntry:function(a,b){a instanceof d&&(a.addObserver(k),c[b]=a,k());return b},getEntry:function(a){return c[a]},
findTabId:function(a){var b=[];if(a)for(var d in c)c[d].tabId===a&&b.push(d);return 0<b.length?b:void 0},removeAllTabIds:function(){for(var a in c)c[a].tabId=void 0},removeTabId:function(a){if(a){for(var b in c)c[b].tabId===a&&(c[b].tabId=void 0);k()}},deleteOrphans:function(a){for(var b=[],d=a.length,f=0;f<d;f++){var h=a[f];if(!h.isDirectory){var h=h.fullPath,g;g=void 0;if(h){var l=void 0;for(l in c)if(c[l].privateFilePath===h||c[l].downloadFilePath===h){g=l;break}}if(!c[g]||c[g].hasExpired())b.push(h),
delete c[g]}}k();return b},cleanUpStore:function(a){for(var b in c)a.includes(b)&&delete c[b];k()},window__:function(){return window}}});
(function(d,c){"function"===typeof define&&define.amd?define("background/chromeHandler",["background/store/fileStore","background/store/fileDetails"],c):d.ChromeHandler=c(d.FileStore,d.FileDetails)})("undefined"!==typeof self?self:this,function(d,c){function a(a,c,d,e){var g=a.length,p=[];return c?h(c,a[0],d):m(e).catch(function(){return k()}).catch(function(){return n()}).catch(function(){return b()}).then(function(b){if(l(b)){for(var c=0;c<g;c++)0===c&&b.useTabId?p.push(h(b.useTabId,a[c],d)):p.push(f(b.id,
a[c],d));return Promise.all(p)}throw Error("Could not find valid window");}).catch(function(a){console.log(a)})}function k(){return new Promise(function(a,b){chrome.windows.getLastFocused({populate:!1},function(c){e(c,a,b)})})}function m(a){return new Promise(function(b,c){chrome.windows.get(a,{populate:!1},function(a){e(a,b,c)})})}function n(){return new Promise(function(a,b){chrome.windows.getCurrent({populate:!1},function(c){e(c,a,b)})})}function b(){return new Promise(function(a,b){chrome.windows.create({type:"normal",
focused:!0},function(c){l(c)?(c.useTabId=c.tabs[0].id,a(c)):b(Error("invalid window"))})})}function e(a,b,c){l(a)?b(a):c(Error("invalid window"))}function f(a,b,c){var d={active:c?c:!1,windowId:a,url:"../views/app.html?uuid="+b};return new Promise(function(a){chrome.tabs.create(d,a)})}function h(a,b,c){var e={active:c?c:!1,url:"../views/app.html?uuid="+b};return new Promise(function(c,f){var g=d.getEntry(b);g?(g.tabId=a,chrome.tabs.update(a,e,c)):f()})}function g(a){return a&&void 0!==a.id}var l=
function(a){return a&&void 0!==a.id&&!a.incognito};return{init:function(){return d.init()},handleIncomingMsg:function(a,b){"driveEnabled"===b.msg&&a.postMessage({driveEnabled:!0,supportsTeamDrives:!0})},handleChromeOSFile:function(a){a=new c({userFile:a.entry,mimeType:a.type});return d.addEntry(a)},handleDriveDoc:function(b,e){var f;if(b){for(var g=[],h=0;h<b.length;++h){var l=new c({driveDocId:b[h],driveDocResourceKey:e?e[b[h]]:void 0}),l=d.addEntry(l);0===h?f=l:g.push(l)}return 0===g.length?Promise.resolve(f):
a(g).then(function(){return f})}return Promise.reject(Error("No drive doc ids were passed to open"))},handleNewCreate:function(b,e,f){l=g;var h=[];b=new c({newDocument:b,mimeType:e});h.push(d.addEntry(b));f=a(h,void 0,!0,f);f.catch(function(a){console.log(a)});return f}}});
(function(d,c){"function"===typeof define&&define.amd?define("background/backgroundMain",["background/store/fileStore","background/chromeHandler"],c):c(d.FileStore,d.ChromeHandler)})("undefined"!==typeof self?self:this,function(d,c){function a(a){if(a&&(a=a["Content-Disposition"]||a["content-disposition"]))try{return a.split("=")[1].trim().replace(/\"/g,"")}catch(c){ErrorCatcher.handleError(new QOWTSilentError("Failed to parse Content-Disposition Header: "+c))}}function k(b,e){try{var f,h;if(b.newCreate)e({newCreate:"Creating new document"}),
c.handleNewCreate(b.newCreate,b.mimeType,b.currentWindowId);else if("getFileDetails"===b.type){var g=d.getEntry(b.uuid);g.mimeType?(h=Object.assign({},g,{mimeType:g.mimeType,originalURL:g.originalURL,streamURL:g.streamURL,userFile:g.userFile}),e(h)):g.driveDocId_?(h=Object.assign({},g,{driveDocId:g.driveDocId_}),e(h)):e(g)}else if("cacheTabId"===b.type)(f=d.getEntry(b.uuid))&&b.tabId&&(f.tabId=b.tabId),e({success:!0});else if("cachePrivateFilePath"===b.type)(f=d.getEntry(b.uuid))&&b.privatePath&&
(f.privateFilePath=b.privatePath),e({success:!0});else if("cacheDownloadFile"===b.type){if(f=d.getEntry(b.uuid))f.downloadFilePath=b.downloadFilePath;e({success:!0})}else if("cacheTimestamp"===b.type){if(f=d.getEntry(b.uuid))f.timestamp=(new Date).getTime();e({success:!0})}else if("fileHandler"===b.type){var l=JSON.parse(b.fileEntries),k=c.handleChromeOSFile(l[0]);e({uuid:k})}else if("addfileStoreMissingEntry"===b.type)l=JSON.parse(b.fileEntries),k=b.uuid,f=new FileDetails({userFile:l[0].entry,mimeType:l[0].type}),
k=d.addMissingEntry(f,k),e({uuid:k});else if("registerMimeHandlerStream"===b.type){var m=JSON.parse(b.streamInfo),k=d.addEntry(new FileDetails({mimeType:m.mimeType,streamURL:m.streamUrl,originalURL:m.originalUrl,tabId:m.tabId,preferredFilename:a(m.responseHeaders),embedded:m.embedded}));e({uuid:k})}else"cleanUpStore"===b.type?(0<b.uuids.length&&d.cleanUpStore(b.uuids),n=void 0,e({success:!0})):"cleanPrivateFiles"===b.type?n?e(!1):(n=b.tabId,e(!0)):"handleDriveDoc"===b.type?c.handleDriveDoc(b.docIds,
b.resourceKeys).then(function(a){e({uuid:a})}).catch(function(a){e(a)}):e(b.type+" is yet to be implemented")}catch(q){console.log(q),e({error:q.message})}return!0}var m=!1;(function(){var a=chrome&&chrome.runtime&&chrome.runtime.onConnectExternal&&chrome.runtime.onConnectExternal.addListener;a||console.warn("Missing Chrome Connect API... drive integration wont work");return a})()&&chrome.runtime.onConnectExternal.addListener(function(a){a.onDisconnect.addListener(function(){});a.onMessage.addListener(function(d){try{c.handleIncomingMsg(a,
d)}catch(f){console.log(f)}})});var n;chrome.tabs.onRemoved.addListener(function(a){a===n&&(n=void 0);d.findTabId(a)&&d.removeTabId(a)});chrome.runtime.onMessage.addListener(function(a,d,f){m?k(a,f):c.init().then(function(){m=!0;k(a,f)});return!0})});
