/*
 RequireJS domReady 2.0.1 Copyright (c) 2010-2012, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/requirejs/domReady for details
 MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors */
define("third_party/domready/domReady",[],function(){function d(){if(!e){e=!0;f&&clearInterval(f);var a=m;if(e&&a.length){m=[];var b;for(b=0;b<a.length;b+=1)a[b](k)}}}function b(a){e?a(k):m.push(a);return b}var c,a,f,g="undefined"!==typeof window&&window.document,e=!g,k=g?document:null,m=[];if(g){if(document.addEventListener)document.addEventListener("DOMContentLoaded",d,!1),window.addEventListener("load",d,!1);else if(window.attachEvent){window.attachEvent("onload",d);a=document.createElement("div");
try{c=null===window.frameElement}catch(h){}a.doScroll&&c&&window.external&&(f=setInterval(function(){try{a.doScroll(),d()}catch(b){}},30))}"complete"===document.readyState&&d()}b.version="2.0.1";b.load=function(a,c,d,f){f.isBuild?d(null):b(d)};return b});
define("qowtRoot/utils/typeUtils",[],function(){function d(a,b,d){if(d.types.every(function(a){var b=c[a];if(!b)throw Error("Bad config to checkArgTypes: unknown type: "+a);return!b(d.value)})){var e=1===d.types.length?d.types[0]:"["+d.types.join(",")+"]";throw Error("Argument "+b+" passed to function "+a+" was supposed to be of type "+e+" but had value "+d.value);}}var b={checkArgTypes:function(a,b){for(var c in b){var e={value:b[c][0],types:b[c].slice(1)};d(a,c,e)}},isObject:function(a){return"object"===
typeof a&&null!==a},isPromise:function(a){return a instanceof Promise},isPromiseLike:function(a){return!(!a||!b.isFunction(a.then))},isList:function(a){return"[object Array]"===Object.prototype.toString.call(a)},isNumber:function(a){return"number"===typeof a&&!isNaN(a)},isInteger:function(a){return"number"===typeof a&&parseInt(a,10)===a},isFunction:function(a){return"function"===typeof a},isString:function(a){return"[object String]"===Object.prototype.toString.call(a)},isRegex:function(a){return"[object RegExp]"===
Object.prototype.toString.call(a)},isNode:function(a){return a instanceof Node},isNull:function(a){return null===a},isUndefined:function(a){return void 0===a},isBoolean:function(a){return"boolean"===typeof a},getType:function(a){var b;Object.keys(c).forEach(function(d){c[d](a)&&(b=d)});return b},isArgumentsObjectOrList:function(a){return a instanceof Object&&a.hasOwnProperty("length")},extend:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},createNewType:function(a){var b=function(){},
d={isOfType:function(a){return void 0!==a&&null!==a&&a.constructor===b},markAsType:function(a){Object.defineProperty(a,"constructor",{value:b,configurable:!1,writable:!1,enumerable:!1});return a}};if(a){if(c[a])throw Error("Already registered type "+a);c[a]=d.isOfType}return d}},c={string:b.isString,object:b.isObject,promise:b.isPromise,promiseLike:b.isPromiseLike,node:b.isNode,regex:b.isRegex,"function":b.isFunction,number:b.isNumber,list:b.isList,boolean:b.isBoolean,"null":b.isNull,undefined:b.isUndefined};
return b});(function(){var d={},b=window.sessionStorage.getItem("featureOverrides");b&&(d=JSON.parse(b));d.isRelease=!0;d.edit=!1;window.sessionStorage.setItem("featureOverrides",JSON.stringify(d));window.localStorage.removeItem("testsToInclude");window.localStorage.removeItem("builtInTests")})();define("configs/releaseFeatures",function(){});
(function(){var d={},b=window.sessionStorage.getItem("featureOverrides");b&&(d=JSON.parse(b));d.save=!!(window.chrome&&window.chrome.fileSystem&&window.chrome.fileSystem.chooseEntry);window.sessionStorage.setItem("featureOverrides",JSON.stringify(d))})();define("configs/chromeFeatures",function(){});define("qowtRoot/features/pack",[],function(){return{edit:!0,save:!1,pointEdit:!1,hats:!0}});
define("qowtRoot/features/utils",["qowtRoot/features/pack"],function(d){var b={isEnabled:function(a){a=d[a];return void 0===a?!1:a},enable:function(a){d[a]=!0},disable:function(a){d[a]=!1},setOverrides:function(a){for(var b in a)a.hasOwnProperty(b)&&(d[b]=a[b])},isDebug:function(){return void 0!==c?c:!b.isEnabled("isRelease")},setDebugOverride:function(a){c=a},clearDebugOverride:function(){c=void 0}},c;return b});
(function(d){d("qowtRoot/third_party/when/lib/timer",["require"],function(b){return{set:setTimeout,clear:clearTimeout}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/lib/timed",[],function(){return function(b,c,a){a.prototype.delay=function(a){var c=this;return new this.constructor(function(d,k,m){c.then(function(c){b(function(){d(c)},a)},k,m)})};a.prototype.timeout=function(a,d){var e=this,k=1<arguments.length;return new this.constructor(function(m,h,q){var n=b(function(){h(k?d:Error("timed out after "+a+"ms"))},a);e.then(function(a){c(n);m(a)},function(a){c(n);h(a)},q)})};return a}})})("function"===typeof define&&define.amd?
define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/array",[],function(){return function(b){var c=Array.prototype.map,a=Array.prototype.reduce,d=Array.prototype.reduceRight,g=Array.prototype.forEach,e=b.resolve,k=b.all;b.any=function(a){return new b(function(b,c){function d(a){k.push(a);0===--f&&c(k)}var f=0,k=[];g.call(a,function(a){++f;e(a).then(b,d)});0===f&&b()})};b.some=function(a,c){return new b(function(b,d,f){function k(a){0<l&&(--l,u.push(a),0===l&&b(u))}function t(a){0<r&&(--r,y.push(a),0===r&&
d(y))}var l=0,r,u=[],y=[];g.call(a,function(a){++l;e(a).then(k,t,f)});c=Math.max(c,0);r=l-c+1;l=Math.min(c,l);0===l&&b(u)})};b.settle=function(a){return k(c.call(a,function(a){function b(){return a.inspect()}a=e(a);return a.then(b,b)}))};b.map=function(a,b,d){return k(c.call(a,function(a){return e(a).then(b,d)}))};b.reduce=function(b,c){function d(a,b,f){return e(a).then(function(a){return e(b).then(function(b){return c(a,b,f)})})}return 2<arguments.length?a.call(b,d,arguments[2]):a.call(b,d)};b.reduceRight=
function(a,b){function c(a,d,f){return e(a).then(function(a){return e(d).then(function(c){return b(a,c,f)})})}return 2<arguments.length?d.call(a,c,arguments[2]):d.call(a,c)};b.prototype.spread=function(a){return this.then(k).then(function(b){return a.apply(void 0,b)})};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/fatal",["require","./timer"],function(b){var c=b("./timer").set;return function(a){c(function(){throw a;},0)}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/lib/flow",["require","./fatal"],function(b){function c(){throw new TypeError("catch predicate must be a function");}function a(a,b){return function(){a.call(this);return b}}function d(){}var g=b("./fatal");return function(b){function k(a,b){return function(c){return(b===Error||null!=b&&b.prototype instanceof Error?c instanceof b:b(c))?a.call(this,c):h(c)}}var m=b.resolve,h=b.reject,q=b.prototype["catch"];b.prototype.done=function(a,b){var c=this._handler;
c.when(this._maybeFatal,d,this,c.receiver,a,b)};b.prototype._maybeFatal=function(a){if(Object(a)===a)m(a)["catch"](this._fatal)};b.prototype._fatal=g;b.prototype["catch"]=b.prototype.otherwise=function(a){return 1===arguments.length?q.call(this,a):"function"!==typeof a?this.ensure(c):q.call(this,k(arguments[1],a))};b.prototype["finally"]=b.prototype.ensure=function(b){if("function"!==typeof b)return this;b=a(b,this);return this.then(b,b)};b.prototype["else"]=b.prototype.orElse=function(a){return this.then(void 0,
function(){return a})};b.prototype.yield=function(a){return this.then(function(){return a})};b.prototype.tap=function(a){return this.then(a).yield(this)};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});(function(d){d("qowtRoot/third_party/when/lib/inspect",[],function(){return function(b){b.prototype.inspect=function(){return this._handler.inspect()};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/iterate",[],function(){return function(b){function c(a,b,k,m){function h(h){return d(k(h)).then(function(){return c(a,b,k,a(h))})}return d(m).then(function(a){return d(b(a)).then(function(b){return b?a:h(a)})})}function a(b,c,k,m){function h(h,m){return d(k(h)).then(function(){return a(b,c,k,m)})}return d(m).then(function(a){return d(c(a)).then(function(c){return c?a:d(b(a)).spread(h)})})}var d=b.resolve;b.iterate=c;b.unfold=a;return b}})})("function"===
typeof define&&define.amd?define:function(d){module.exports=d()});(function(d){d("qowtRoot/third_party/when/lib/progress",[],function(){return function(b){b.prototype.progress=function(b){return this.then(void 0,void 0,b)};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/with",[],function(){return function(b){b.prototype["with"]=b.prototype.withThis=b.prototype._bindContext;return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/makePromise",[],function(){return function(b){function c(b){var c=this;this._handler=new n;a(b,function(a){c._handler.resolve(a)},function(a){c._handler.reject(a)},function(a){c._handler.notify(a)})}function a(a,b,c,d){try{a(b,c,d)}catch(f){c(f)}}function d(a){return new g(new x(new r(a)))}function g(a){this._handler=a}function e(a,b){if(a instanceof c){var d=a._handler.join();return b===d?new r(new TypeError("Promise cycle")):d}return I(a)?m(a):new l(a)}
function k(a){return a instanceof c?a._handler.join():m(a)}function m(a){try{var b=a.then;return"function"===typeof b?new t(b,a):new l(a)}catch(c){return new r(c)}}function h(){}function q(a){this.handler=a;if(this._isMonitored()){var b=this._env.promiseMonitor.captureStack();this.trace=a._addTrace(b)}}function n(a){this.consumers=[];this.receiver=a;this.handler=void 0;this.resolved=!1;this._isMonitored()&&(this.trace=this._env.promiseMonitor.captureStack())}function x(a){q.call(this,a)}function A(a,
b){q.call(this,a);this.receiver=b}function t(a,b){n.call(this);this.assimilated=!1;this.untrustedThen=a;this.thenable=b}function l(a){this.value=a}function r(a){this.value=a;this.observed=!1;this._isMonitored()&&(this.key=this._env.promiseMonitor.startTrace(a))}function u(){return{state:"pending"}}function y(a,b,c,d,f,g,k,z){this.a=a;this.b=b;this.c=c;this.d=d;this.e=f;this.f=g;this.g=k;this.handler=z}function D(a,b){this.q=a;this.value=b}function I(a){return("object"===typeof a||"function"===typeof a)&&
null!==a}function J(a,b,c){try{return a.call(c,b)}catch(g){return d(g)}}function v(){}var H,B=b.scheduler,w=Object.create||function(a){function b(){}b.prototype=a;return new b};c.resolve=function(a){return a instanceof c?a:new g(new x(e(a)))};c.reject=d;c.never=function(){return H};c._defer=function(){return new g(new n)};c.prototype.then=function(a,b,c){var d=this._handler,f=new n(d.receiver);d.when(f.resolve,f.notify,f,d.receiver,a,b,c);return new g(f)};c.prototype["catch"]=c.prototype.otherwise=
function(a){return this.then(void 0,a)};c.prototype._bindContext=function(a){return new g(new A(this._handler,a))};c.all=function(a){function b(a,c,d,z){d.when(v,v,void 0,a,function(a){c[z]=a;0===--f&&this.resolve(c)},a.reject,a.notify)}var c=new n,d=a.length>>>0,f=d,e=[],h,z;for(h=0;h<d;++h)h in a?(z=a[h],I(z)?b(c,e,k(z),h):(e[h]=z,--f)):--f;0===f&&c.resolve(e);return new g(c)};c.race=function(a){if(Object(a)===a&&0===a.length)return H;for(var b=new n,c=0;c<a.length;++c)e(a[c]).when(v,v,void 0,b,
b.resolve,b.reject);return new g(b)};g.prototype=w(c.prototype);h.prototype.inspect=u;h.prototype.when=v;h.prototype.resolve=v;h.prototype.reject=v;h.prototype.notify=v;h.prototype.join=function(){return this};h.prototype._env=b.monitor||c;h.prototype._addTrace=v;h.prototype._isMonitored=function(){return"undefined"!==typeof this._env.promiseMonitor};q.prototype=w(h.prototype);q.prototype.join=function(){return this.handler.join()};q.prototype.inspect=function(){return this.handler.inspect()};q.prototype._addTrace=
function(a){return this.handler._addTrace(a)};n.prototype=w(h.prototype);n.prototype.inspect=function(){return this.resolved?this.handler.join().inspect():u()};n.prototype.resolve=function(a){this._join(e(a,this))};n.prototype.reject=function(a){this._join(new r(a))};n.prototype.join=function(){return this.resolved?this.handler.join():this};n.prototype.run=function(){var a=this.consumers,b=this.handler=this.handler.join();this.consumers=void 0;for(var c=0;c<a.length;c+=7)b.when(a[c],a[c+1],a[c+2],
a[c+3],a[c+4],a[c+5],a[c+6])};n.prototype._join=function(a){this.resolved||(this.resolved=!0,this.handler=a,B.enqueue(this),this._isMonitored()&&(this.trace=a._addTrace(this.trace)))};n.prototype.when=function(a,b,c,d,f,g,e){this.resolved?B.enqueue(new y(a,b,c,d,f,g,e,this.handler.join())):this.consumers.push(a,b,c,d,f,g,e)};n.prototype.notify=function(a){this.resolved||B.enqueue(new D(this.consumers,a))};n.prototype._addTrace=function(a){return this.resolved?this.handler._addTrace(a):a};x.prototype=
w(q.prototype);x.prototype.when=function(a,b,c,d,f,g,e){B.enqueue(new y(a,b,c,d,f,g,e,this.join()))};A.prototype=w(q.prototype);A.prototype.when=function(a,b,c,d,f,g,e){void 0!==this.receiver&&(d=this.receiver);this.join().when(a,b,c,d,f,g,e)};t.prototype=w(n.prototype);t.prototype.when=function(a,b,c,d,f,g,e){this.assimilated||(this.assimilated=!0,this._assimilate());n.prototype.when.call(this,a,b,c,d,f,g,e)};t.prototype._assimilate=function(){var a=this;this._try(this.untrustedThen,this.thenable,
function(b){a.resolve(b)},function(b){a.reject(b)},function(b){a.notify(b)})};t.prototype._try=function(a,b,c,d,f){try{a.call(b,c,d,f)}catch(g){d(g)}};l.prototype=w(h.prototype);l.prototype.inspect=function(){return{state:"fulfilled",value:this.value}};l.prototype.when=function(a,b,c,d,f){b="function"===typeof f?J(f,this.value,d):this.value;a.call(c,b)};r.prototype=w(h.prototype);r.prototype.inspect=function(){return{state:"rejected",reason:this.value}};r.prototype.when=function(a,b,c,g,e,k){this._isMonitored()&&
!this.observed&&this._env.promiseMonitor.removeTrace(this.key);this.observed=!0;b="function"===typeof k?J(k,this.value,g):d(this.value);a.call(c,b)};r.prototype._addTrace=function(a){this.observed||this._env.promiseMonitor.updateTrace(this.key,a)};H=new g(new h);y.prototype.run=function(){this.handler.when(this.a,this.b,this.c,this.d,this.e,this.f,this.g)};D.prototype.run=function(){for(var a=this.q,b=1;b<a.length;b+=7)this._notify(a[b],a[b+1],a[b+2],a[b+5])};D.prototype._notify=function(a,b,c,d){var f;
if("function"===typeof d)try{f=d.call(c,this.value)}catch(g){f=g}else f=this.value;a.call(b,f)};return c}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/Queue",[],function(){function b(b){this.head=this.tail=this.length=0;this.buffer=Array(1<<b)}b.prototype.push=function(b){this.length===this.buffer.length&&this._ensureCapacity(2*this.length);this.buffer[this.tail]=b;this.tail=this.tail+1&this.buffer.length-1;++this.length;return this.length};b.prototype.shift=function(){var b=this.buffer[this.head];this.buffer[this.head]=void 0;this.head=this.head+1&this.buffer.length-1;--this.length;return b};b.prototype._ensureCapacity=
function(b){var a=this.head,d=this.buffer,g=Array(b),e=0,k;if(0===a)for(k=this.length;e<k;++e)g[e]=d[e];else{b=d.length;for(k=this.tail;a<b;++e,++a)g[e]=d[a];for(a=0;a<k;++e,++a)g[e]=d[a]}this.buffer=g;this.head=0;this.tail=this.length};return b})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/scheduler",["require","./Queue"],function(b){function c(b){this._enqueue=b;this._handlerQueue=new a(15);var c=this;this.drainQueue=function(){c._drainQueue()}}var a=b("./Queue");c.prototype.enqueue=function(a){1===this._handlerQueue.push(a)&&this._enqueue(this.drainQueue)};c.prototype._drainQueue=function(){for(var a=this._handlerQueue;0<a.length;)a.shift().run()};return c})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/lib/async",["require"],function(b){var c;return"undefined"!==typeof process&&null!==process&&"function"===typeof process.nextTick?function(a){process.nextTick(a)}:(c="function"===typeof MutationObserver&&MutationObserver||"function"===typeof WebKitMutationObserver&&WebKitMutationObserver)?function(a,b){var c,d=a.createElement("div");(new b(function(){var a=c;c=void 0;a()})).observe(d,{attributes:!0});return function(a){c=a;d.setAttribute("class","x")}}(document,
c):function(a){var b=setTimeout;return function(a){b(a,0)}}(b)})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});(function(d){d("qowtRoot/third_party/when/lib/Promise",["require","./makePromise","./scheduler","./async"],function(b){var c=b("./makePromise"),a=b("./scheduler");b=b("./async");return c({scheduler:new a(b),monitor:"undefined"!==typeof console?console:void 0})})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/when","require ./lib/timer ./lib/timed ./lib/array ./lib/flow ./lib/inspect ./lib/iterate ./lib/progress ./lib/with ./lib/Promise".split(" "),function(b){function c(a,b,c,d){var f=r(a);return 2>arguments.length?f:f.then(b,c,d)}function a(a){return function(){return g(a,this,u.call(arguments))}}function d(a){return g(a,this,u.call(arguments,1))}function g(a,b,c){return l.all(c).then(function(c){return a.apply(b,c)})}function e(){function a(b){d._handler.resolve(b)}
function b(a){d._handler.reject(a)}function c(a){d._handler.notify(a)}var d=l._defer();this.promise=d;this.resolve=a;this.reject=b;this.notify=c;this.resolver={resolve:a,reject:b,notify:c}}var k=b("./lib/timer"),m=b("./lib/timed"),h=b("./lib/array"),q=b("./lib/flow"),n=b("./lib/inspect"),x=b("./lib/iterate"),A=b("./lib/progress"),t=b("./lib/with"),l=b("./lib/Promise"),l=[h,q,x,A,n,t].reduceRight(function(a,b){return b(a)},m(k.set,k.clear,l)),r=l.resolve,u=Array.prototype.slice;c.promise=function(a){return new l(a)};
c.resolve=l.resolve;c.reject=l.reject;c.lift=a;c["try"]=d;c.attempt=d;c.iterate=l.iterate;c.unfold=l.unfold;c.join=function(){return l.all(arguments)};c.all=function(a){return c(a,l.all)};c.settle=function(a){return c(a,l.settle)};c.any=a(l.any);c.some=a(l.some);c.map=function(a,b){return c(a,function(a){return l.map(a,b)})};c.reduce=function(a,b){var d=u.call(arguments,1);return c(a,function(a){d.unshift(a);return l.reduce.apply(l,d)})};c.reduceRight=function(a,b){var d=u.call(arguments,1);return c(a,
function(a){d.unshift(a);return l.reduceRight.apply(l,d)})};c.isPromiseLike=function(a){return a&&"function"===typeof a.then};c.Promise=l;c.defer=function(){return new e};return c})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
define("qowtRoot/utils/promiseUtils",["qowtRoot/utils/typeUtils","qowtRoot/third_party/when/when"],function(d,b){var c={cast:function(a){return a instanceof Promise?a:Promise.resolve(a)},delay:function(a,b){a=a||0;return new Promise(function(c){setTimeout(c.bind(void 0,b),a)})},delayThenReject:function(a,b){a=a||0;return new Promise(function(c,d){setTimeout(d.bind(c,b),a)})},throwAndEscapeChain:function(a){a instanceof Error||(console.error("throwAndEscapeChain wrapping value in new Error: ",a),a=
Error(a));b.reject(a).done();throw a;},pipeline:function(a){function b(){for(var e=Array.prototype.slice.call(arguments,0);0<a.length;){var m=a.shift();if(d.isPromiseLike(m))return c.cast(m).then(function(c){a.unshift(c);return b.apply(g,e)});d.checkArgTypes("PromiseUtils.pipeline",{task:[m,"function"]});m=m.apply(g,e);if(d.isPromiseLike(m))return c.cast(m).then(function(a){return b(a)});e=[m]}return e[0]}var g=this,e=Array.prototype.slice.call(arguments,0);if(e.some(d.isPromiseLike))return Promise.all(e).then(function(a){return c.pipeline.apply(g,
a)});d.checkArgTypes("PromiseUtils.pipeline",{tasks:[a,"list"]});a=a.slice(0);return b.apply(g,e.slice(1))},finally:function(a,b){function d(){return c.cast(b()).then(function(){return a})}return c.cast(a).then(d,d)},waitForNextMacroTurn:function(a){return new Promise(function(b){window.setTimeout(b.bind(null,a),0)})}};return c});
define("qowtRoot/utils/platform",[],function(){var d=Object.create(Object.prototype,{name:{get:function(){return b}},locale:{get:function(){return c}},isOther:{get:function(){return"OTHER"===b}},isUnix:{get:function(){return"UNIX"===b}},isWindows:{get:function(){return"WINDOWS"===b}},isOsx:{get:function(){return"OSX"===b}},isLinux:{get:function(){return"LINUX"===b}},isCros:{get:function(){return"CROS"===b}}}),b,c;(function(){b="OTHER";var a=navigator.appVersion.toLowerCase();-1!==a.indexOf("x11")&&
(b="UNIX");-1!==a.indexOf("win")&&(b="WINDOWS");-1!==a.indexOf("mac")&&(b="OSX");-1!==a.indexOf("linux")&&(b="LINUX");-1!==a.indexOf("cros")&&(b="CROS");c=navigator.language.toUpperCase()})();return d});
define("utils/analytics/googleAnalytics",["qowtRoot/features/utils","qowtRoot/utils/promiseUtils","qowtRoot/utils/platform"],function(d,b,c){function a(a,b){var c;void 0!==E?c=E?Promise.resolve():Promise.reject(Error("ga permission cached (not permitted)")):(chrome&&chrome.metricsPrivate&&chrome.metricsPrivate.getIsCrashReportingEnabled&&(!d.isDebug()||void 0!==window.__gaMock)?c=Promise.resolve():(console.warn("GA not supported on this platform"),c=Promise.reject(Error("GA not supported on this platform"))),
c=c.then(f).catch(k));return c.then(m).then(a.bind(null,b)).catch(function(){})}function f(){var a=Error("Crash reporting setting timed out");return Promise.race([g(),b.delayThenReject(1E3,a)]).then(e)}function g(){return new Promise(function(a){chrome.metricsPrivate.getIsCrashReportingEnabled(a)})}function e(a){return new Promise(function(b,c){window.__gaMock&&(C=window.__gaMock.ga4TestUpdate(B));(E=a)?b():(console.warn("Crash reporting not allowed"),c())})}function k(){E=!1;return Promise.reject()}
function m(){void 0===F&&h("QO");return Promise.resolve()}function h(a){if(F=a)G=a,q(G);window.__gaMock&&C.setTracker(v[a]);return Promise.resolve()}function q(a){w!==a&&(G=w=a,window.__gaMock&&C.sendState(a),t({name:"page_view"}));return Promise.resolve()}function n(a){var b={name:"exception",parameters:{}};b.parameters.description=a.msg;b.parameters.fatal=a.fatal;window.__gaMock&&C.sendException(a.msg,a.fatal);t(b);return Promise.resolve()}function x(a){if(6E4>=a.value)return"Percentile99th";if(6E4<
a.value&&12E5>=a.value)return"Percentile99.90th";if(12E5<a.value)return"Percentile99.99th"}function A(a){window.__gaMock&&(y(),C.sendEvent(a.category,a.action,p));t(a);return Promise.resolve()}function t(a){var b=v[F],c=H[F];a.name=a.name?a.name:a.action;I().then(function(d){try{fetch(J+"?measurement_id="+b+"&api_secret="+c,{method:"POST",body:JSON.stringify({client_id:d,timestamp_micros:1E3*(new Date).getTime(),events:[D(a)]})})}catch(f){console.error("Google Analytics request failed with an exception",
f)}})}function l(a){if("10.0"===a)return"10";if("6.2"===a)return"8";if("6.1"===a)return"7";if("6.0"===a)return"Vista";if("5.1"===a)return"XP";if("5.0"===a)return"2000";a}function r(){return new Promise(function(a,b){var c="Unknown";if(navigator.userAgentData)navigator.userAgentData.getHighEntropyValues(["fullVersionList"]).then(function(b){c=(b=b.fullVersionList.find(function(a){return"Google Chrome"===a.brand}))?b.version:"Unknown";a(c)}).catch(function(a){b("Error retrieving User-Agent data: "+
a)});else{var d=navigator.userAgent;d.includes("Chrome")&&(c=(d=d.match(/Chrome\/([\d.]+)/))?d[1]:"Unknown");a(c)}})}function u(){var a,b=/\(([^)]+)\)/.exec(navigator.userAgent)[1];c.isCros&&-1!==b.indexOf("CrOS")?a=b.match(/CrOS.*\d+(?:\.\d+)+/)[0].replace("CrOS ",""):c.isLinux&&-1!==b.indexOf("Linux")?a=/[^ ]*$/.exec(b)[0]:c.isOsx&&-1!==b.indexOf("Mac OS X")?(a=b.match(/\d+[._]\d+(?:[._]\d+)?/)[0].replaceAll("_","."),1<a.match(/\./g).length&&(a=a.match(/^(\d+\.\d+)/)[0])):c.isWindows&&-1!==b.indexOf("Windows")&&
(a=b.match(/\d+(?:\.\d+)+/)[0],a=l(a));return a}function y(){p||(p={},r().then(function(a){p.browser_version=a}),p.engagement_time_msec=100,p.session_id=window.__gaMock?"":L,p.app_version=window.__gaMock?"":chrome.runtime.getManifest().version,p.user_language=c.locale,p.operating_system="LINUX"===c.name?"Linux":"WINDOWS"===c.name?"Windows":"CROS"===c.name?"Chrome OS":"OSX"===c.name?"Macintosh":c.name,p.screen_resolution=window.screen.width+"x"+window.screen.height,p.viewport=window.innerWidth+"x"+
window.innerHeight,p.operating_system_version=u(),p.app_name=B)}function D(a){var b=a.name.replaceAll("-","_");y();p.page_title=G;"CC"===a.action&&"performance-metrics"===a.category?p.percentile_type=x(a):"CR"===a.action&&"performance-metrics"===a.category&&(p.percentile_type=x(a));if(!a.parameters||"exception"!==a.name&&"page_view"!==a.name)p.event_category=a.category,a.label&&(p.event_label=a.label),a.value&&(p.value=a.value);else for(var c=Object.keys(a.parameters),d=0;d<c.length;d++)p[c[d]]=a.parameters[c[d]];
return{name:b,params:p}}function I(){K||(K=new Promise(function(a,b){chrome.storage.sync.get("clientId",function(c){if(chrome.runtime.lastError)b(chrome.runtime.lastError);else if("undefined"===typeof c.clientId){var d=self.crypto.randomUUID();c={};c.clientId=d;chrome.storage.sync.set(c,function(){a(d)})}else a(c.clientId)})}));return K}var J="https://www.google-analytics.com/mp/collect",v={word:"G-2EHQ55R09Q",sheet:"G-429ETHTJYR",point:"G-5VSRBT2L9W",QO:"G-11BCJ4LWCJ"},H={word:"esgLzn1kRb6eHxjysYicgQ",
sheet:"v9vcbIqZSe6pTYEryGsfUQ",point:"5uHsbBE-Q3-tHRTfVqEEXg",QO:"k2-sQUVpTZWoDAUgoGUwog"},B="Quickoffice",w,E,C,L,F,G,p,K;return{setFileExt:function(a){},setSessionGroup:function(a){L=a},setTracker:function(b){return a(h,b)},sendState:function(b){return a(q,b)},sendException:function(b){return a(n,b)},sendEvent:function(b){return a(A,b)},getMeasurementId:function(a){return v[a]},reset:function(){G=F=C=E=w=void 0}}});
define("qowtRoot/utils/i18n",["qowtRoot/utils/typeUtils","utils/analytics/googleAnalytics"],function(d,b){var c={getMessage:function(a,b){var g="????";if(!chrome||!chrome.i18n)return a;d.isString(a)?(g=chrome.i18n.getMessage(a,b),g||(g=a,c.logError_("Missing translation",a))):c.logError_("Invalid string translation Id",a);return g},logError_:function(a,c){console.error(a+" "+c);b.sendException({msg:a,fatal:!1})}};return c});
require(["third_party/domready/domReady!"],function(){require(["qowtRoot/utils/i18n"],function(d){var b=d.getMessage("extension_popup_new_document_header");document.getElementById("newHeading").textContent=b;var b=d.getMessage("extension_popup_new_spreadsheet_document"),b=createOption(b,"sheet"),c=d.getMessage("extension_popup_new_presentation_document"),c=createOption(c,"point"),a=d.getMessage("extension_popup_new_word_document"),a=createOption(a,"word"),f=document.getElementById("options");f.appendChild(b);
f.appendChild(c);f.appendChild(a);document.getElementById("messageBody").innerHTML=d.getMessage("extension_popup_message_body")})});function createOption(d,b){var c=document.createElement("div");c.id=b;c.textContent=d;var a=document.createElement("a");a.textContent=d;a.href="#";c.addEventListener("click",onClick,!0);return c}
function onClick(d){var b;"word"===d.target.id?b="application/vnd.openxmlformats-officedocument.wordprocessingml.document":"point"===d.target.id?b="application/vnd.openxmlformats-officedocument.presentationml.presentation":"sheet"===d.target.id&&(b="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");chrome.windows.getCurrent(function(c){chrome.runtime.sendMessage({newCreate:d.target.id,mimeType:b,currentWindowId:c.id},function(){window.close()})})}define("mainPopup",function(){});
